default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: nformacy
  password: password
  pool: 5

development:
  <<: *default
  database: task_development


test:
  <<: *default
  database: task_test
